#' Heatmap representation of markers median values in meta-clusters.
#'
#' @param TreeMetaCl Object generated by the function BuildFSOMTree
#' @param Markers vector of Markers
#' @param clustering if true, a hierarichal clustring is applied to the heatmap
#' @param Quartile if true, plot quartile 1 and 3 for each meta-cluster instead of median
#' @return a heatmap figure
#' @export

HeatMapTree = function(TreeMetaCl,Markers,clustering = T,Quartile = F) {
  if (length(intersect(Markers,TreeMetaCl$fSOMTree$prettyColnames)) < 1) {stop("Marker not found")}
  print(paste("Use markers ",paste(intersect(Markers,TreeMetaCl$fSOMTree$prettyColnames),collapse=" "),sep=""))
  MarkerList = unlist(sapply(intersect(Markers,TreeMetaCl$fSOMTree$prettyColnames),function(Marker){
    MarkerIndex=which(TreeMetaCl$fSOMTree$prettyColnames == Marker)
    unlist(sapply(unique(TreeMetaCl$metaCl),function(MetaCl){
      clusterList=which(TreeMetaCl$metaCl == MetaCl)
      metaClustIndices=unlist(sapply(clusterList,
                                     function(cluster){which(TreeMetaCl$fSOMTree$map$mapping[,1] == cluster)}))
      if (Quartile) {return(as.vector(quantile(TreeMetaCl$fSOMTree$data[metaClustIndices,MarkerIndex],na.rm=T))[2:4])} else
      {return(median(TreeMetaCl$fSOMTree$data[metaClustIndices,MarkerIndex],na.rm=T))}
    }))
  }))
  print(MarkerList)

  if (Quartile) {
    MarkerMatrix=matrix(MarkerList[-((1:(length(MarkerList)/3))*3-1)],nrow=length(unique(TreeMetaCl$metaCl))*2,
                        dimnames = list(kronecker(unique(TreeMetaCl$metaCl),c("1Q","3Q"),function(x,y){paste(x,y,sep="_")}),
                                        intersect(Markers,TreeMetaCl$fSOMTree$prettyColnames)))
    MedianMatrix = matrix(MarkerList[((1:(length(MarkerList)/3))*3-1)],nrow=length(unique(TreeMetaCl$metaCl)),
                          dimnames = list(unique(TreeMetaCl$metaCl),intersect(Markers,TreeMetaCl$fSOMTree$prettyColnames)))
  }
  else {
  MarkerMatrix=matrix(MarkerList,nrow=length(unique(TreeMetaCl$metaCl)),
                      dimnames = list(unique(TreeMetaCl$metaCl),intersect(Markers,TreeMetaCl$fSOMTree$prettyColnames)))
}
  colMarginSize=20-18*exp(-max(sapply(colnames(MarkerMatrix),nchar))/10)
  rowMarginSize=20-18*exp(-max(sapply(row.names(MarkerMatrix),nchar))/10)
  colCex4Plot=exp(-max(sapply(colnames(MarkerMatrix),nchar))/70)*exp(-length(colnames(MarkerMatrix))/50)
  rowCex4Plot=exp(-max(sapply(row.names(MarkerMatrix),nchar))/70)*exp(-length(row.names(MarkerMatrix))/50)



  if (clustering) {
    if (Quartile) {
    matrix4Dist = apply(MedianMatrix,2,function(l){rbind(l,l)})
    heatmap.2ClustMat(MarkerMatrix,clustMat = matrix4Dist,scale = "column",col = gplots::bluered(100),trace = "none",density.info = "none",
              margins=c(colMarginSize,rowMarginSize),cexRow = rowCex4Plot,cexCol=colCex4Plot)}

    else
  {gplots::heatmap.2(MarkerMatrix,scale = "column",col = gplots::bluered(100),trace = "none",density.info = "none",
                    margins=c(colMarginSize,rowMarginSize),cexRow = rowCex4Plot,cexCol=colCex4Plot)}}
  else {gplots::heatmap.2(MarkerMatrix,scale = "column",col = gplots::bluered(100),trace = "none",density.info = "none",
    Rowv=F,Colv=F,dendrogram = "none",margins=c(colMarginSize,rowMarginSize),cexRow = rowCex4Plot,cexCol=colCex4Plot)}
}
