#'
#'Plot Tree and display the choosen number of clusters and metaclusters
#' @param fSOM Object generated by buildFSOMTree function
#' @param mainTitle Title of your experiment
#' @param nbRm Number of the smallest clusters to remove for effective visualization of the tree
#' @return Plot the tree generated by buildFSOMTree function with informationns about the number of choosen clusters and metaclusters.
#' 
#'

PlotTreeMSTRm <- function(fSOM,mainTitle,nbRm)
{
  fSOM4Plot=list(
    map=fSOM$fSOMTree$map,
    prettyColnames=fSOM$fSOMTree$prettyColnames,
    MST=fSOM$fSOMTree$MST)
  if (nbRm>0)
  {
    indexKeep =  which(fSOM$fSOMTree$MST$size > sort(fSOM$fSOMTree$MST$size)[nbRm])
    indexRemove  = setdiff((1:length(fSOM$fSOMTree$MST$size)),indexKeep)
    fSOM4Plot$MST$size=fSOM$fSOMTree$MST$size[indexKeep]
    fSOM4Plot$map$medianValues=fSOM$fSOMTree$map$medianValues[indexKeep,]
    fSOM4Plot$MST$graph=igraph::induced_subgraph(fSOM$fSOMTree$MST$graph,indexKeep)
    fSOM4Plot$MST$l = fSOM$fSOMTree$MST$l[indexKeep,]
    PlotStarsBigLeg(fSOM4Plot,backgroundValues = as.factor(fSOM$metaCl[indexKeep]), 
                    main=paste(mainTitle,"_",fSOM$gatingName,"_Clusters=",fSOM$fSOMTree$map$nNodes,"_Metaclusters=",length(unique(fSOM$metaCl))))
  }
  else
  {PlotStarsBigLeg(fSOM4Plot,backgroundValues = as.factor(fSOM$metaCl), 
                   main=paste(mainTitle,"_",fSOM$gatingName,"_Clusters=",fSOM$fSOMTree$map$nNodes,"_Metaclusters=",length(unique(fSOM$metaCl))))}
  
}
