#' Plot2DScatterPlot
#' 
#' Plot2DScatterPlot creates a matrix through the "pairs" function displaying the raw data pool of all fcs files in 2D scatter plots.
#' @param TreeMetaCl object generated by buildFSOMTree function
#' @param Title title of the matrix
#' @return PDF file of the matrix 2D scatter plot saved in the working directory 
#' @examples Plot2DScatterPlot(TreeMetaCl=CytoTree,Title="Experiment 1")
#' @export

#Plot2DScatterPlot function
Plot2DScatterPlot<-function(TreeMetaCl,Title){
  
  #Creates data frame with for each cell, the corresponding cluster, metacluster and every marker's expression
  ClustersData<-as.data.frame(TreeMetaCl$fSOMTree$map$mapping)
  MarkersData<-as.data.frame(TreeMetaCl$fSOMTree$data)
  PrettyNames<-as.data.frame(TreeMetaCl$fSOMTree$prettyColnames)
  PrettyNames$UglyNames<-row.names(PrettyNames)
  names(PrettyNames)[1]<-"PrettyNames"
  colnames(MarkersData)<-PrettyNames$PrettyNames[match(colnames(MarkersData),PrettyNames$UglyNames)]
  FrameMarkers<-cbind(ClustersData,MarkersData)
  names(FrameMarkers)[1]<-"Clusters"
  MetaclFrame<-as.data.frame(TreeMetaCl$metaClNumber)
  MetaclFrame$Clusters<-c(1:nrow(MetaclFrame))
  names(MetaclFrame)[1]<-"Metaclusters"
  FrameMarkers$Metaclusters<-MetaclFrame[match(x=FrameMarkers$Clusters, table = MetaclFrame$Clusters),"Metaclusters"]
  
  #plot 2D scatter plot matrix
  
  pdf(file=paste(Title),"2D_Scatterplot.pdf")
  pairs(FrameMarkers[,!names(FrameMarkers) %in% c("Clusters","V2","Time","Metaclusters")],
                 lower.panel=NULL,main=Title,pch=20)
  dev.off()
}
