#' ScatterPlotMatrix
#' 
#' ScatterPlotMatrix creates a matrix of scatter plot through the "pairs" function displaying the raw data pool of all fcs files.
#' @param TreeMetaCl object generated by buildFSOMTree function
#' @param Title title of the matrix
#' @return PDF file of the matrix plot saved in the working directory 
#' @examples ScatterPlotMatrix(CytoTree,"Experiment 1")
#' @export


ScatterPlotMatrix<-function(TreeMetaCl,Title){
  
  ClustersData<-as.data.frame(TreeMetaCl$fSOMTree$map$mapping)
  MarkersData<-as.data.frame(TreeMetaCl$fSOMTree$data)
  PrettyNames<-as.data.frame(TreeMetaCl$fSOMTree$prettyColnames)
  PrettyNames$UglyNames<-row.names(PrettyNames)
  names(PrettyNames)[1]<-"PrettyNames"
  colnames(MarkersData)<-PrettyNames$PrettyNames[match(colnames(MarkersData),PrettyNames$UglyNames)]
  FrameMarkers<-cbind(ClustersData,MarkersData)
  names(FrameMarkers)[1]<-"Clusters"
  MetaclFrame<-as.data.frame(TreeMetaCl$metaClNumber)
  MetaclFrame$Clusters<-c(1:nrow(MetaclFrame))
  names(MetaclFrame)[1]<-"Metaclusters"
  FrameMarkers$Metaclusters<-MetaclFrame[match(x=FrameMarkers$Clusters, table = MetaclFrame$Clusters),"Metaclusters"]
  
  
  pdf(file=paste(Title),"Scatterplot_Matrix.pdf")
  pairs(FrameMarkers[,!names(FrameMarkers) %in% c("Clusters","V2","Time","Metaclusters")],
        lower.panel=NULL,main=Title,pch=20)
  dev.off()
}
