#' Selective naming of metaclustesters according to specific markers expression
#' @param TreeMetaCl Object generated by the function BuildFSOMTree
#' @param Markers Markers choosen for the naming
#' @param NameType Type of name applied
#' @return BuildFSOMTree object with the metaclusters renamed with the choosen name type
#' @export 


TreeMetaRenaming<-function(TreeMetaCl,Markers,NameType){
  
  TreeMetaCl$metaClNumber=TreeMetaCl$metaCl
  Namings=MetaClusterNaming(TreeMetaCl,Markers)
  TreeMetaCl$metaCl=sapply(TreeMetaCl$metaCl,function(x){paste(Namings$number[which(Namings$number == x)],
                                                           Namings$option[which(Namings$number == x)],sep="_")})
  return()
  }



devtools::document