#' Selective naming of metaclustesters according to specific markers expression
#'
#' TreeMetaRenaming is a function that allows the automatic renaming of the metaclusters according to their expression for specific markers. If this function is applied, the metaclusters will be renamed for the following commands of the script.
#' @param TreeMetaCl Object generated by the function BuildFSOMTree
#' @param Markers Markers choosen for the naming
#' @param NameType Type of name applied, that is ""nonRobustName","robustName" or "shortRobustName"
#' @return BuildFSOMTree object with the metaclusters renamed with the choosen name type, keeping the metacluster numbers ($metaClNumber)
#' @examples CytoTree=TreeMetaRenaming(TreeMetaCl=CytoTree,Markers=c("CD4","CD8","FoxP3"),NameType="shortRobustName")
#' @export


TreeMetaRenaming<-function(TreeMetaCl,Markers,NameType="shortRobustName"){
  if (is.null(TreeMetaCl$gatingName)) {gName = ""} else
  {gName=TreeMetaCl$gatingName}
  Namings=MetaClusterNaming(TreeMetaCl,Markers)
  return(list(fSOMTree=TreeMetaCl$fSOMTree,
              metaClNumber=TreeMetaCl$metaCl,
              metaCl=
                sapply(TreeMetaCl$metaCl,function(x){paste(Namings$number[which(Namings$number == x)],
                                                                       Namings[[NameType]][which(Namings$number == x)],sep="_")}),
              gatingName=gName))
  }
